# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Manash Kumar Mandal
email: manashmndl@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio of Manash Kumar Mandal
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://manash.io"
# url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  manashmandal

# navigation:
#   - title: Home
#     url: /index.html
#   - title: About
#     url: /aboutme.html

# Build settings
markdown: kramdown



theme: jekyll-theme-cayman